name: Build and Deploy to AKS

on:
  push:
    branches: [main]

env:
  ACR_NAME: gvoicecontainerregistery # e.g., myacrname
  ACR_LOGIN_SERVER: gvoicecontainerregistery.azurecr.io
  AKS_CLUSTER_NAME: AKSCluster
  RESOURCE_GROUP: AKS-testing
  IMAGE_NAME: gvoice-demo-playground
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure ACR login
        run: az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME

      - name: Deploy to AKS
        run: |
          kubectl delete -f .kubernets/deploy-in-cluster.yaml
          kubectl apply -f .kubernets/deploy-in-cluster.yaml
        #kubectl apply -f .kubernets/deploy-in-cluster.yaml
